version: "3.8"

services:
  influx:
    image: influxdb:1.8.10-alpine
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_DB=test
    ports:
      - "8086:8086"
    volumes:
      - ./docker_data/influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana-oss:9.2.6
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - ./docker_data/grafana:/var/lib/grafana
    depends_on:
      - influx
